title: Luc Frachon # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Selected Projects 
  <br><br>
  Who am I?
  <br><br>
  <a href="https://www.linkedin.com/in/lucfrachon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-CNPGRKF9XF # your Google Analytics tracking ID here
